#!/usr/bin/env bash                                                                                                                                       
# fix nginx listening on port 80                                                                                                                          
# Go to folder for Nginx

cd /etc/nginx/sites-enabled/ || exit;                                                                                                                             
# Delete default file                                                                                                                               
rm default;                                                                                                                                               
# Create symbolic link to the deafult file in available site                                                                                            
ln -s /etc/nginx/sites-available/default default;                                                                                                         
# Restar

service nginx restart
