#!/usr/bin/env bash
# Configure ufw firewall to block all incoming traffic
# Except for TCP ports 22, 443 and 80.

sudo apt-get install ufw
sudo ufw status
sudo ufw enable -y
sudo ufw default deny incoming -y
sudo ufw default allow outgoing -y
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcpp
